version: "3.3"

services:
  zimbra:
    image: localhost:5000/zcs-foss-base:latest
    configs:
      - source: init_common
        target: /zimbra/init-common
        mode: 0777
      - source: init_zimbra
        target: /zimbra/init
        mode: 0777
      - source: config_zimbra
        target: /zimbra/config.in
        mode: 0666
    env_file: .env
    entrypoint:
      - /zimbra/init
#    entrypoint:
#      - /bin/sleep
#      - infinity
    hostname: ${ZIMBRA_HOST_NAME}
    networks:
      - default
    ports:
      - "7071:7071"
      - "8143:143"
      - "8443:443"
      - "8993:993"

  mailbox:
    image: localhost:5000/zcs-foss-base:latest
    configs:
      - source: init_common
        target: /zimbra/init-common
        mode: 0777
      - source: init_mailbox
        target: /zimbra/init
        mode: 0777
      - source: config_mailbox
        target: /zimbra/config.in
        mode: 0666
    env_file: .env
    entrypoint:
      - /zimbra/init
#    entrypoint:
#      - /bin/sleep
#      - infinity
    hostname: ${MAILBOX_HOST_NAME}
    networks:
      - default

configs:
  init_common:
    file: ./configs/init-common
  init_mailbox:
    file: ./configs/init-mailbox
  config_mailbox:
    file: ./configs/config-mailbox
  init_zimbra:
    file: ./configs/init-zimbra
  config_zimbra:
    file: ./configs/config-zimbra
     

networks:
  default:
    driver: overlay
